devices:
  R1:
    container: clab-srl-lab-R1
    platform: srlinux
    role: router

  R2:
    container: clab-srl-lab-R2
    platform: srlinux
    role: router

  R3:
    container: clab-srl-lab-R3
    platform: srlinux
    role: router
