devices:
  R1:
    interfaces:
      ethernet-1/1:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.12.1/30
      ethernet-1/2:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.31.1/30

    network_instances:
      default:
        interfaces:
          - ethernet-1/1.0
          - ethernet-1/2.0
          - lo0.0

    ospf:
      instance:
        name: default
        admin_state: enable
        version: ospf-v2
        router_id: 1.1.1.1
        areas:
          0.0.0.0:
            interfaces:
              ethernet-1/1.0: {}
              ethernet-1/2.0: {}
              lo0.0:
                passive: true

  R2:
    interfaces:
      ethernet-1/1:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.12.2/30
      ethernet-1/2:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.23.1/30

    network_instances:
      default:
        interfaces:
          - ethernet-1/1.0
          - ethernet-1/2.0
          - lo0.0

    ospf:
      instance:
        name: default
        admin_state: enable
        version: ospf-v2
        router_id: 2.2.2.2
        areas:
          0.0.0.0:
            interfaces:
              ethernet-1/1.0:
                admin_state: enable
              ethernet-1/2.0:
                admin_state: enable
              lo0.0:
                admin_state: enable
                passive: true

  R3:
    interfaces:
      ethernet-1/1:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.23.2/30
      ethernet-1/2:
        admin_state: enable
        ipv4:
          admin_state: enable
          address: 10.0.31.2/30

    network_instances:
      default:
        interfaces:
          - ethernet-1/1.0
          - ethernet-1/2.0
          - lo0.0

    ospf:
      instance:
        name: default
        admin_state: enable
        version: ospf-v2
        router_id: 3.3.3.3
        areas:
          0.0.0.0:
            interfaces:
              ethernet-1/1.0:
                admin_state: enable
              ethernet-1/2.0:
                admin_state: enable
              lo0.0:
                admin_state: enable
                passive: true
